# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6131e95c9bec8b5190063b9224246d0f93a941cd5830ba658b7aa67b978119c64f44d29f14d31da1771742ce37ec9d660cb2b69cba87e9dda3c2df93c9e7d766
  CLIENT_ID: 561677375968-gb854kduiokeskbjsij8ks323u2m2ruj.apps.googleusercontent.com
  CLIENT_SECRET: owFVJbh65phZn64-zI2ljtDg


test:
  secret_key_base: ecc3a32d99914fd19996f1ef3a6a6189ebfa51716676bd0b5523a5f234e539781c92b1761a4903376ee3105a91c112039ee3e929f2e3362f2e7233bd36e556d3
  CLIENT_ID: 561677375968-gb854kduiokeskbjsij8ks323u2m2ruj.apps.googleusercontent.com
  CLIENT_SECRET: owFVJbh65phZn64-zI2ljtDg


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>